print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call a astronaut\'s cavity?')
input()
print('Black Hole!')
print()
print('Who\'s there?')
input()
print('Interrupting cow.')
input()
print('Interrupting cow wh', end='')
print('-MOO!')
